### ISSUE TITLE
Built-in node modules fs, net, tls not found when project built with Webpack

### ISSUE THREAD

**Issue by Janaka-Steph** [DigixGlobal/truffle-lightwallet-provider#3]
Hello,

When I build my project with Webpack 3 I have errors: node modules fs, net, tls not found.
I tried a bunch of things, setting `target: node` in webpack config, using https://github.com/liady/webpack-node-externals, setting fs, net and tls as "externals". But nothing works. Also I am targeting the web as it is a dapp so `target: node` is not the solution.
Any idea ?
Thank you

**Comment by IstoraMandiri** [comment]
Hmm, this package is not designed for browser usage, and expects filesystem access for grabbing the JSON file. 

I guess we could add support for browser it in the future, so I'll leave this open.

**Comment by Horbi** [comment]
![coins-64x64](https://user-images.githubusercontent.com/25962962/30005238-3bf25448-90de-11e7-8bda-e05e5c360c6b.jpg)
![register-64x64](https://user-images.githubusercontent.com/25962962/30005241-4b9b422e-90de-11e7-9e46-d0b153849295.jpg)
